version: '3'

services:
  web1:
    image: 'metavinayak/matrix'
    ports:
      - '8081:3000'
    volumes:
      - ./logs/web1:/var/log/app  
    
    logging:
      driver: json-file
      
  web2:
    image: 'metavinayak/matrix'
    ports:
      - '8082:3000'
    volumes:
      - ./logs/web2:/var/log/app
    
    logging:
      driver: json-file
      
  web3:
    image: 'metavinayak/matrix'
    ports:
      - '8083:3000'
    volumes:
      - ./logs/web3:/var/log/app  
    
    logging:
      driver: json-file

  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
      - web3

      
